version: '3'

services:
  mysql-docker-container:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=mypass
      - MYSQL_DATABASE=classification
      - MYSQL_USER=ahmet
      - MYSQL_PASSWORD=mypass
    volumes:
      - ./Dump20230129.sql:/docker-entrypoint-initdb.d/Dump20230129.sql
    ports:
      - "3333:3306"
    networks:
      - default
    container_name: classification-db

  chapter-api:
    image: chapterapi-image
    build:
      context: ~/desktop/SymptomChapter
      dockerfile: Dockerfile
    depends_on:
      - mysql-docker-container
    ports:
      - "8090:8090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-docker-container:3306/classification?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: ahmet
      SPRING_DATASOURCE_PASSWORD: mypass
    volumes:
      - /data/chapterapi-app
    networks:
      - default
    container_name: chapterapi-api

  subchapter-api:
    image: subchapterapi-image
    build:
      context: ~/desktop/SymptomSubchapter
      dockerfile: Dockerfile
    depends_on:
      - mysql-docker-container
    ports:
      - "8094:8094"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-docker-container:3306/classification?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: ahmet
      SPRING_DATASOURCE_PASSWORD: mypass
    volumes:
      - /data/subchapterapi-app
    networks:
      - default
    container_name: subchapterapi-api

  secondsubchapter-api:
    image: secondsubchapterapi-image
    build:
      context: ~/desktop/SymptomSecondSubChapter
      dockerfile: Dockerfile
    depends_on:
      - mysql-docker-container
    ports:
      - "8096:8096"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-docker-container:3306/classification?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: ahmet
      SPRING_DATASOURCE_PASSWORD: mypass
    volumes:
      - /data/secondsubchapterapi-app
    networks:
      - default
    container_name: secondsubchapterapi-api

  subtitle-api:
    image: subtitle-image
    build:
      context: ~/desktop/SymptomSubtitle
      dockerfile: Dockerfile
    depends_on:
      - mysql-docker-container
    ports:
      - "8098:8098"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-docker-container:3306/classification?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: ahmet
      SPRING_DATASOURCE_PASSWORD: mypass
    volumes:
      - /data/subtitle-app
    networks:
      - default
    container_name: subtitle-api
networks:
  default:
    external:
      name: classificationnetwork