version: '3'

services:
  chapter-api:
    image: chapterapi-image
    build:
      context: .
    ports:
      - "8090:8090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-docker-container:3306/classification?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: ahmet
      SPRING_DATASOURCE_PASSWORD: mypass
    volumes:
      - /data/chapterapi-app
    networks:
      - default
    container_name: chapterapi-api

networks:
  default:
    external:
      name: classificationnetwork