version: '3'

services:
  symptomclassifier-api:
    image: symptomclassifier-image
    build:
      context: .
    ports:
      - "8090:8090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-docker-container:3306/classification?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: ahmet
      SPRING_DATASOURCE_PASSWORD: mypass
    volumes:
      - /data/symptomclassifier-app
    networks:
      - default
    container_name: symptomclassifier-api

networks:
  default:
    external:
      name: classificationnetwork